[pytest]

# Where pytest should search for test cases
testpaths = tests

;# Test file naming pattern
python_files = test_*.py fedex_*.py icici_*.py hdfc_*.py *_fedex.py *fedex*.py


# Test function naming pattern
python_functions = test_* fedex*, test*,

# Register custom ETL markers
markers =
    etl: ETL validation tests
    smoke: Smoke tests
    regression: Regression tests
    data_quality: Data quality validation tests
    reconciliation: Source-to-target reconciliation tests
    sanity : sanity tests

# Command-line options applied automatically
addopts = -v -s

# Minimum pytest version
minversion = 8.0